version: '3'

services:
  multi:
    container_name: multi
    build:
      # all paths are relative to the location of docker-compose.yml
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      # Modify the first param of the line below with
      # the location of your application when developing
      - .:/var/www/html
      - /home:/home


networks:
  default:
    driver: bridge